import { GoogleGenAI } from "@google/genai";
import { ref, uploadString, getDownloadURL } from "firebase/storage";
import { storage } from "../firebase";

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || "" });

/**
 * Generates or retrieves a cached organelle image from Firebase Storage.
 * @param organelleId Unique identifier for the organelle (used as filename)
 * @param prompt The prompt to generate the image if not cached
 * @returns The download URL of the image
 */
export async function getOrganelleImage(organelleId: string, prompt: string): Promise<string> {
  const storageRef = ref(storage, `organelles/${organelleId}.png`);

  // 1. Try to get existing image from cache (Firebase Storage)
  try {
    const cachedUrl = await getDownloadURL(storageRef);
    console.log(`Using cached image for ${organelleId}`);
    return cachedUrl;
  } catch (error: any) {
    // If error is 404 (not found), proceed to generate
    if (error.code !== 'storage/object-not-found') {
      console.error("Error checking cache:", error);
    }
  }

  // 2. Generate new image if not found in cache
  console.log(`Generating new image for ${organelleId}...`);
  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            text: `${prompt} The subject must be centered on a pure black background. No text, no labels. High quality 3D render.`,
          },
        ],
      },
      config: {
        imageConfig: {
          aspectRatio: "1:1",
        },
      },
    });

    let base64Data = "";
    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        base64Data = part.inlineData.data;
        break;
      }
    }

    if (!base64Data) throw new Error("No image generated by Gemini");

    // 3. Upload to Firebase Storage for future use
    const dataUrl = `data:image/png;base64,${base64Data}`;
    await uploadString(storageRef, dataUrl, 'data_url');
    
    // 4. Return the new download URL
    return await getDownloadURL(storageRef);
  } catch (error) {
    console.error("Error generating or uploading image:", error);
    throw error;
  }
}
